### ISSUE TITLE
Grok Pattern for European Timestamp

### ISSUE THREAD

**Issue by gruselglatz** [reighnman/Graylog_Content_Pack_WinDNS#1]
Hi,

i want to mention that if you have an European Timestamp like "6.11.2015 13:01:29 1274 PACKET...." the GROK-Pattern wont match. You have to Change WINDNS_TIME to "(?:0?[1-9]|1[0-2])[.-](?:%28?:0[1-9]%29|%28?:[12][0-9]%29|%28?:3[01]%29|[1-9])[.-](?>dd){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)" (without Quotes).

And don't forget to add the Static Field: "SourceModuleName: dns" to the DNS-Server GELF-Input if you dont use the Content-Pack generated input.

Kind Regards,
Rene

**Comment by reighnman** [comment]
Can you please try updating the WinDNS_Time GROK pattern to the following and let me know if it continues to match the EU Timestamp? 

WINDNS_TIME:
((?:0?[1-9]|1[0-2])[/-](?:%28?:0[1-9]%29|%28?:[12][0-9]%29|%28?:3[01]%29|[1-9])[/-](?>dd){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)\s(A|P)M|(?:0?[1-9]|1[0-2]).-.-{1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?))

**Comment by gruselglatz** [comment]
Sry for the late Answer, but no it doesn't work with the pattern above.

Here is an example message:

```
07.12.2015 09:49:45 0E1C PACKET  000000AF909625B0 UDP Rcv 212.33.32.97    0055   Q [0001   D   NOERROR] A      (8)hangouts(6)google(3)com(0)
```

**Comment by reighnman** [comment]
@renapu 

Give this a try:

WINDNS_TIME:

```
((?:0?[1-9]|1[0-2])[\/-](?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[\/-](?>\d\d){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)\s(A|P)M)|((?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[\.](?:0?[1-9]|1[0-2])[\.](?>\d\d){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?))
```

**Comment by gruselglatz** [comment]
Nice it's working now! Thank you for fixing this

**Comment by rka** [comment]
Hello i also have a problem with the time i think:

2016.03.02. 21:26:49 08B8 PACKET  0000000003DF9A10 UDP Rcv 172.16.2.57     c6e3   Q [0001   D   NOERROR] A      (9)PC-737-11(7)hivatal(13)erzsebetvaros(2)hu(0)

I tried all of the above windns time patterns

thanks in advance

Im really shit with regex but its working now :)

([0-9]{4}[^0-9]_[0-9]{2}[^0-9]_[0-9]{2}..([01]\d|2[0-3]):[0-5]\d:[0-5]\d)

edit2:

([0-9]{4}[^0-9][0-9]{2}[^0-9][0-9]{2}..(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)?([0-5]?\d))
