### ISSUE TITLE
Extractor WinDNS_Name not working

### ISSUE THREAD

**Issue by technicallife** [reighnman/Graylog_Content_Pack_WinDNS#10]
Hey there,

the WinDNS_Name extractor is not working it says "Could not load an example of field 'Name'. It is not possible to test the extractor before updating it."

My setup is: Server 2016 
Graylog 3.1.2
Sidecar with Filebeat

any advise? thanks!

**Comment by gonnetl** [comment]
I have the same problem.... :-\
What is the solution please ?

**Comment by 00depps** [comment]
I had to rename the source field from name to host_name. There was no name field in the messages from Beats/My Windows 2016 DNS server.

**Comment by Henkoba** [comment]
I had a similar issue, but my root cause was the grok patterns for time extraction. 

When I updated WINDNS_TIME to match my local locale instead of US time format, the other patterns started to work.
