### ISSUE TITLE
Issue with date format - WINDNS_TIME

### ISSUE THREAD

**Issue by mathieuchateau** [reighnman/Graylog_Content_Pack_WinDNS#12]
I had issue with WINDNS_TIME, as our AD Servers are in French, date format is French.

I replaced with this grok pattern :
%{MONTHDAY}/%{MONTHNUM}/%{YEAR} %{HOUR}:%{MINUTE}:%{SECOND}

It's not useful but then extractor started to work

**Comment by Henkoba** [comment]
Similar issue, but Swedish locale.

I had to set WINDNS_TIME to:
%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:%{MINUTE}:%{SECOND}
