### ISSUE TITLE
Can not get the Grok pattern to work

### ISSUE THREAD

**Issue by Pajje99** [reighnman/Graylog_Content_Pack_WinDNS#2]
HI!

I'm exited to test tis contentpack but can not get it to work right.

It installs fine but i does not extract messages right. Whe i try the Grok pattern it say 

Attention
We were not able to run the grok extraction. Please check your parameters.

I have tied it both with and without the Grok Pattern for European Timestamp but it does not work.

i get the following in the messages: 

message
2015-12-07 21:22:15 12CC PACKET  000000E647BF8180 UDP Snd 172.17
![screenshot](https://cloud.githubusercontent.com/assets/16124303/11638799/156bec58-9d29-11e5-95d9-86b26668e110.PNG)

Regards Per-Åke

**Comment by reighnman** [comment]
Try updating WINDNS_TIME to:

```
((?:0?[1-9]|1[0-2])[\/\.-](?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[\/\.-](?>\d\d){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)\s(A|P)M)|((?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[\/\.-](?:0?[1-9]|1[0-2])[\/\.-](?>\d\d){1,2}\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)|((?>\d\d){1,2}[\/\.-](?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[\/\.-](?:0?[1-9]|1[0-2])\s(?!<[0-9])(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)))
```

Through the web-interface that is, you would have to escape all the slashes to directly edit the .json file

**Comment by Pajje99** [comment]
It's working now. Thank you!!!
