### ISSUE TITLE
Extractors not running on Win2012 R2

### ISSUE THREAD

**Issue by doomguy** [reighnman/Graylog_Content_Pack_WinDNS#3]
Hi there,
I set everything up as described on a Windows Server 2012 R2 + NxLog-CE and I'm receiving DNS request logs inside graylog2 latest (1.3.3).However, it seems like the extractors don't run on the incoming messages. Validating the Extractors by hand with a previous collected message works though (see attachment).

Example Log Entry:

```
24.01.2016 18:17:42 045C PACKET  000000A5B1285F80 UDP Rcv 119.160.247.124 be20 R Q [0084 A     NOERROR] A      (5)yahoo(2)de(0)
```

Any ideas on whats going wrong there?

[graylog-windns-win2k12r2-manual-verify.pdf](https://github.com/reighnman/Graylog_Content_Pack_WinDNS/files/102586/graylog-windns-win2k12r2-manual-verify.pdf)

**Comment by 1mr** [comment]
Have the same issue. Was fixed. I create the extractor manually.  
![screen shot 2016-02-10 at 11 24 40 pm](https://cloud.githubusercontent.com/assets/1835287/12962281/7c0251da-d04d-11e5-8b29-c78c8f0dfabc.png)

**Comment by reighnman** [comment]
Is that the latest revision you installed?  I noticed in your pdf attachment Name still has (#), this was replaced by periods in the latest revision.

**Comment by reighnman** [comment]
I will look into this with the 2.0 release.

**Comment by reighnman** [comment]
I'm going to chalk this up as a bug for now and see if it comes back in 2.0.  Please try the solution proposed by @1mr
