### ISSUE TITLE
MapperParsingException[failed to parse [ThreadID]

### ISSUE THREAD

**Issue by rka** [reighnman/Graylog_Content_Pack_WinDNS#6]
Hello,

I installed the new 2.1.1 graylog OVA image, and i tried to set up the usual stuff when i got this problem. In older versions i just used this:

```
curl -XPUT localhost:9200/_template/graylog -d '
{
  "template":"graylog*",
  "settings":{
    "index.refresh_interval":"30s"
    },
    "mappings":{
      "message":{
        "properties":{
          "ThreadID":{
            "index":"not_analyzed",
            "type":"String"
          }
        }
      }
    }
}'
```

Now this is not working. Then i tried creating a new index template like here:
http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html?highlight=graylog-custom-mapping#creating-a-new-index-template

I created the graylog-custom-mapping.json

```
{
  "template":"graylog*",
  "settings":{
    "index.refresh_interval":"30s"
    },
    "mappings":{
      "message":{
        "properties":{
          "ThreadID":{
            "index":"not_analyzed",
            "type":"String"
          }
        }
      }
    }
}

```
And then:

`curl -X PUT -d @'graylog-custom-mapping.json' 'http://172.16.1.41:9200/_template/graylog-custom-mapping?pretty`'

But it's still dropping errors (tried to restart, reconfigure, delete the server and then start fresh but nothing)

`MapperParsingException[failed to parse [ThreadID]]; nested: NumberFormatException[For input string: "092C"];`

What am i doing wrong :(

**Comment by reighnman** [comment]
More than likely it's an elasticsearch version compatibility issue.  I still run 2.4 which I deployed to a new build recently so I know that works, its possibly they changed the dynamic template format in 5+.

I'm not sure what version you're running so might want to check that out.

**Comment by reighnman** [comment]
Also verify your incidies begin with graylog (if you changed it to something other than default then you have to update the filter)

**Comment by adam-wood** [comment]
For future people looking at this and the solution from @rka , I found that I needed to change the case of 'String' to 'string' in graylog-custom-mapping.json as below.

Using
- Elasticsearch 5.x
- Graylog 2.4

`{
  "template":"graylog*",
  "settings":{
    "index.refresh_interval":"30s"
    },
    "mappings":{
      "message":{
        "properties":{
          "ThreadID":{
            "index":"not_analyzed",
            "type":"string"
          }
        }
      }
    }
}`
