### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dbarajas1** [reighnman/Graylog_Content_Pack_WinDNS#8]
In Version 2.3.x it is not possible to create an custom index template for ThreadID field. All values "index":"not_analyzed", 
"type":"String" can't set. 

Any fix for this? I'm not sure if this is the reason I can't get any data showing when I look at the dashboard. 

Thanks

**Comment by 123dev** [comment]
Try type "text"

**Comment by dbarajas1** [comment]
I have changed that and still nothing.

I can see the DNS messages. Just not seeing anything on the dashboard.

```
EventReceivedTime

2017-10-09 11:54:53
SourceModuleName

dns
SourceModuleType

im_file
level

6
message

10/9/2017 11:54:42 AM 0A74 PACKET  0000000002780650 UDP Rcv xxx.xx.x.xx     9b24   Q [0001   D   NOERROR] AAAA   (12)video-ort2-1(2)xx(5)fbcdn(3)net(0)
source

HQ-xxxx
timestamp

2017-10-09T18:54:53.000Z
```

**Comment by 123dev** [comment]
Did you rotate active write index? and then narrow the search window to match the time range after doing the rotation.

Any errors in the logs?

**Comment by reighnman** [comment]
The threadid index template was just to fix a certain condition where after an index rotation the first message received contained a threadid of all integers which would cause elastic to auto set the field as INT, which would cause index errors for any following messages where threadid's contained alphanumeric.

Elastic is much further along now so I haven't tested what the fix would be on newer versions, but in general the indexing should work unless that condition occurs.  Are you seeing index errors as the messages are not being indexed at all it looks like.

**Comment by dbarajas1** [comment]
Not seeing index errors. But just not seeing the extractors WinDNS_Name or WinDNS_Debug_Log have hits. 

I have verified the extractors are part of the Input the logs are being sent to. Just not seeing anything happen. Is there something that is missing here?

**Comment by reighnman** [comment]
retro
