### ISSUE TITLE
Cannot import Content PAck

### ISSUE THREAD

**Issue by kartone** [reighnman/Graylog_Content_Pack_WinDNS#9]
With Graylog 3.1.0 this content pack would not be imported with this error: 

> Could not import content pack
> Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information.<br /><small>Null id at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1da06c7d; line: 207, column: 1] (through reference chain: org.graylog2.contentpacks.model.AutoValue_LegacyContentPack$Builder["id"])</small>

**Comment by reighnman** [comment]
Content pack has been rebuilt for 3.1, please test.
